In [1]:
import numpy as np
mylist = [1,2,3]

In [2]:
mylist

[1, 2, 3]

In [3]:
#轉換成numpy array
np.array(mylist)

array([1, 2, 3])

In [4]:
myarray = np.array([1, 2, 3])

In [5]:
myarray

array([1, 2, 3])

In [6]:
mylist = [1,2.0,"abc",True]
mylist

[1, 2.0, 'abc', True]

In [7]:
np.array(mylist) #放入Numpy後會把所有類型都轉成Str

array(['1', '2.0', 'abc', 'True'], dtype='<U32')

In [8]:
a  = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [9]:
type(a) #裡面的n可以解釋為N-dimension 多維度

numpy.ndarray

In [10]:
a.ndim

1

In [11]:
a.shape #成員

(6,)

In [14]:
a = a.reshape(2,3)#改成兩個row 三個Column

In [15]:
a.ndim

2

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a.shape 

(2, 3)

In [18]:
a = a.reshape(1,6)

In [19]:
a.ndim

2

In [20]:
a

array([[1, 2, 3, 4, 5, 6]])

In [21]:
a = a.reshape(2,3)

In [22]:
a.ndim

2

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a = np.array([1,2,3,4,5,6])

In [25]:
a.ndim

1

In [26]:
a = np.array([[1,2,3,4,5,6]])

In [27]:
a.ndim

2

In [28]:
a.shape 

(1, 6)

In [29]:
a = np.array([[[1,2,3,4,5,6]]])

In [30]:
a.ndim

3

In [31]:
a.shape 

(1, 1, 6)