In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [3]:
#如果修改第一個成員值
a[0] = 10

In [4]:
a

array([10,  1,  2,  3])

In [5]:
a.dtype

dtype('int32')

In [6]:
a[0] = 10.8

In [7]:
a

array([10,  1,  2,  3])

In [8]:
a = np.array([1,2,3,4])

In [9]:
a.dtype

dtype('int32')

In [10]:
a = np.array([1,3,4.0,5])

In [11]:
a

array([1., 3., 4., 5.])

In [12]:
a.dtype

dtype('float64')

In [14]:
a = np.array([1,2,3,4.0],dtype = "int32")

In [16]:
a.dtype

dtype('int32')

In [18]:
c = np.array([[10,11,12],[20,32,30]])

In [19]:
c

array([[10, 11, 12],
       [20, 32, 30]])

In [20]:
c.dtype

dtype('int32')

In [21]:
c.ndim

2

In [23]:
c.shape#(Row,Column)

(2, 3)