In [1]:
import numpy as np

In [4]:
np.random.rand(2) #0~1數字

array([0.65366022, 0.18971276])

In [5]:
np.random.rand(5,4) #0~1數字

array([[0.08347014, 0.97893036, 0.14224898, 0.34171598],
       [0.97128154, 0.79547478, 0.45222161, 0.3569754 ],
       [0.24524676, 0.61669577, 0.096744  , 0.57463465],
       [0.87494896, 0.50060623, 0.5531631 , 0.41017155],
       [0.86125489, 0.61161332, 0.13795594, 0.92375692]])

In [6]:
np.random.randn(5,4) #無限大~無限小

array([[-0.05413335, -0.29876695,  0.04938972, -0.15652822],
       [ 0.2361751 ,  0.38009942, -0.47862441,  0.7183433 ],
       [-0.03179825,  0.25361949, -1.96803502,  1.00012464],
       [-0.66920386, -0.49732849, -1.33252807, -0.4144246 ],
       [ 1.7949613 , -0.44471133, -0.27808899,  0.18050995]])

In [11]:
np.random.randint(1,100,(6,5))#隨機的整數

array([[34, 63,  4, 84, 28],
       [67, 79, 17, 96, 73],
       [97, 83, 46, 27, 76],
       [88, 90, 48, 58, 14],
       [47, 70, 10, 43, 46],
       [88, 59, 24, 31,  2]])

In [12]:
np.random.randint(1,100,25)#隨機的整數

array([92, 80, 37, 76, 10, 18, 98, 94, 72, 85,  2, 92, 90,  9, 66, 37, 64,
       24, 21, 47, 14, 82, 23, 16,  8])

In [17]:
np.random.randint(1,100,25).reshape(25,1)

array([[43],
       [69],
       [49],
       [71],
       [19],
       [27],
       [62],
       [70],
       [55],
       [90],
       [78],
       [22],
       [66],
       [98],
       [35],
       [51],
       [62],
       [26],
       [78],
       [89],
       [10],
       [ 4],
       [85],
       [ 9],
       [69]])

In [18]:
randarr = np.random.randint(1,100,25).reshape(5,5)

In [20]:
randarr 

array([[33, 83, 64, 46, 59],
       [44, 77, 51, 12, 36],
       [18, 64, 32, 65, 14],
       [86, 24, 17, 33, 80],
       [84, 24, 93, 27, 71]])

In [22]:
#取得最大值
randarr.max()

93

In [23]:
randarr.argmax() #取得最大值的Index

22

In [24]:
randarr.min()

12

In [25]:
randarr.argmin()

8