In [1]:
import numpy as np

In [3]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
a[:,1::2] #只能冒號在後面

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [7]:
a[4,:]# 20 21 22 23 24

array([20, 21, 22, 23, 24])

In [9]:
#5 7 15 17
a[1::2,:3:2]

array([[ 5,  7],
       [15, 17]])

In [10]:
#另外一種方式
a[1::2,:4:2]

array([[ 5,  7],
       [15, 17]])

In [11]:
a[1::2,:-1:2]

array([[ 5,  7],
       [15, 17]])

In [12]:
a[1::2,:-2:2]

array([[ 5,  7],
       [15, 17]])

In [13]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
new_array = a[:,1::2]

In [16]:
#修改裡面的值
new_array

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

In [17]:
#修改23
new_array[4,1] = 0

In [18]:
new_array

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21,  0]])

In [19]:
another_array = new_array.copy() #複製新的Array

In [21]:
another_array[4,1] = 10

In [22]:
another_array

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 10]])

In [23]:
new_array

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21,  0]])

In [24]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22,  0, 24]])