In [1]:
#var[lower:upper:step]

In [8]:
import numpy as np

In [3]:
              #-5 -4 -3 -2 -1
              #0  1  2  3  4
a = np.array([10,11,12,13,14])

In [7]:
a[1:3]

array([11, 12])

In [9]:
a[-4:-2]

array([11, 12])

In [10]:
a[-4:-1]

array([11, 12, 13])

In [12]:
a[-4:4]

array([11, 12, 13])

In [14]:
#忽略內容 讀取10 11 12
a[:3]

array([10, 11, 12])

In [15]:
a[-2:]

array([13, 14])

In [17]:
#10 12 14
a[::2]

array([10, 12, 14])

In [18]:
a = np.arange(25).reshape(5,5)

In [19]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
#希望讀取3,4
a[0,3:5] #row,column

array([3, 4])

In [21]:
#18 ,19 ,23 ,24
a[3:,3:]

array([[18, 19],
       [23, 24]])

In [22]:
#2,7,12,17,22
a[:,2]

array([ 2,  7, 12, 17, 22])

In [24]:
#10 12 14 20 22 24
a[2::2,::2]

array([[10, 12, 14],
       [20, 22, 24]])

Object `np.arange` not found.
