In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])

In [3]:
a

array([1, 2, 3, 4, 5, 6])

In [4]:
b = np.array(a).reshape((3,2))

In [5]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
b.ndim

2

In [7]:
a.ndim

1

In [8]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [11]:
a = np.arange(0,11)

In [12]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#每個數字相差二
a = np.arange(0,11,2)

In [14]:
a

array([ 0,  2,  4,  6,  8, 10])

In [15]:
b = np.linspace(0,11,11) #固定範圍，平均分

In [16]:
b

array([ 0. ,  1.1,  2.2,  3.3,  4.4,  5.5,  6.6,  7.7,  8.8,  9.9, 11. ])

In [17]:
type(1)

int

In [18]:
type(1.2)

float

In [19]:
np.zeros(3) #裡面都是0的數值

array([0., 0., 0.])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones(3)

array([1., 1., 1.])

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])